/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/myoperator/podrestartoperator/pkg/apis/podrestarter/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePodReStarters implements PodReStarterInterface
type FakePodReStarters struct {
	Fake *FakeApiV1alpha1
	ns   string
}

var podrestartersResource = schema.GroupVersionResource{Group: "api.practice.com", Version: "v1alpha1", Resource: "podrestarters"}

var podrestartersKind = schema.GroupVersionKind{Group: "api.practice.com", Version: "v1alpha1", Kind: "PodReStarter"}

// Get takes name of the podReStarter, and returns the corresponding podReStarter object, and an error if there is any.
func (c *FakePodReStarters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Podrestarter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(podrestartersResource, c.ns, name), &v1alpha1.Podrestarter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Podrestarter), err
}

// List takes label and field selectors, and returns the list of PodReStarters that match those selectors.
func (c *FakePodReStarters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PodrestarterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(podrestartersResource, podrestartersKind, c.ns, opts), &v1alpha1.PodrestarterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PodrestarterList{ListMeta: obj.(*v1alpha1.PodrestarterList).ListMeta}
	for _, item := range obj.(*v1alpha1.PodrestarterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested podReStarters.
func (c *FakePodReStarters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(podrestartersResource, c.ns, opts))

}

// Create takes the representation of a podReStarter and creates it.  Returns the server's representation of the podReStarter, and an error, if there is any.
func (c *FakePodReStarters) Create(ctx context.Context, podReStarter *v1alpha1.Podrestarter, opts v1.CreateOptions) (result *v1alpha1.Podrestarter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(podrestartersResource, c.ns, podReStarter), &v1alpha1.Podrestarter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Podrestarter), err
}

// Update takes the representation of a podReStarter and updates it. Returns the server's representation of the podReStarter, and an error, if there is any.
func (c *FakePodReStarters) Update(ctx context.Context, podReStarter *v1alpha1.Podrestarter, opts v1.UpdateOptions) (result *v1alpha1.PodReStarter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(podrestartersResource, c.ns, podReStarter), &v1alpha1.Podrestarter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Podrestarter), err
}

// Delete takes name of the podReStarter and deletes it. Returns an error if one occurs.
func (c *FakePodReStarters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(podrestartersResource, c.ns, name), &v1alpha1.Podrestarter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePodReStarters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(podrestartersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PodrestarterList{})
	return err
}

// Patch applies the patch and returns the patched podReStarter.
func (c *FakePodReStarters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Podrestarter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(podrestartersResource, c.ns, name, pt, data, subresources...), &v1alpha1.Podrestarter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Podrestarter), err
}
