/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	podrestarterv1alpha1 "github.com/myoperator/podrestartoperator/pkg/apis/podrestarter/v1alpha1"
	versioned "github.com/myoperator/podrestartoperator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/myoperator/podrestartoperator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/myoperator/podrestartoperator/pkg/client/listers/podrestarter/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodReStarterInformer provides access to a shared informer and lister for
// PodReStarters.
type PodReStarterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PodReStarterLister
}

type podReStarterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodReStarterInformer constructs a new informer for PodReStarter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodReStarterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodReStarterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodReStarterInformer constructs a new informer for PodReStarter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodReStarterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().PodReStarters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().PodReStarters(namespace).Watch(context.TODO(), options)
			},
		},
		&podrestarterv1alpha1.Podrestarter{},
		resyncPeriod,
		indexers,
	)
}

func (f *podReStarterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodReStarterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podReStarterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&podrestarterv1alpha1.Podrestarter{}, f.defaultInformer)
}

func (f *podReStarterInformer) Lister() v1alpha1.PodReStarterLister {
	return v1alpha1.NewPodReStarterLister(f.Informer().GetIndexer())
}
