apiVersion: api.practice.com/v1alpha1
kind: Podrestarter
metadata:
  name: mypodrestarter
spec:
  restart: "false"
  deployment_name: my-deployment
  deployment_namespace: default
  replicas: 2
  images:
    - image: nginx:1.18-alpine
    - image: busybox



